id: AE8344912
title: Brief Confession to the Earth Lords
type: translation
pechas:
- I45676884
- I2E56D4AD
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:34.452291
  last_modified_at: 2023-01-04 12:45:34.452296
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I45676884/CB08: A8B5
  I2E56D4AD/112B: A8B5
